version: '0.0.0-{branch}-{build}'
init:
  - git config --global core.autocrlf true
image: Visual Studio 2017    
branches:
  only:
    - master
    - dev
    - /^update[0-9]{3}/
install:
  - ps: scripts\appveyor_install.ps1
test_script:
  - ps: scripts\appveyor_tests.ps1
build_script:
  - ps: scripts\appveyor_build.ps1
artifacts:
  - path: '**\*.nupkg'
deploy:
- provider: NuGet
  server: https://www.myget.org/F/oss-ci/api/v2/package
  artifact: /.*\.nupkg/
  skip_symbols: true
  api_key:
    secure: 1P+0B28UVI3VKxuJhVuO7V/r3lVCudwiup9kHJrCiC1IkM1XxJWuGflkJRtF/M3e
  on:
    appveyor_repo_tag: true
- provider: NuGet
  artifact: /.*\.nupkg/
  skip_symbols: true
  api_key:
    secure: yaNSoFafxc5LNvb8gfvmwluoRaEFUW89IWi8QAl/bIhnFty4FWQ1NpoUT+5f5R/c
  on:
    appveyor_repo_tag: true
